version: 2.1
orbs:
  heroku: circleci/heroku@2.0
jobs:
  build:
    docker:
      - image: cimg/deploy:2023.04-node
        environment:
          DOCKER_HOST: tcp://localhost:2375
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm run test:coverage -- --coverage
            ./cc-test-reporter after-build --exit-code $?
      - run:
          name: Install Heroku CLI
          command: |
              curl https://cli-assets.heroku.com/install.sh | sh
      - run:
          name: Build and push Docker image to Heroku
          command: |
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:login
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:push web --app user-info
              HEROKU_API_KEY=${HEROKU_TOKEN} heroku container:release web --app user-info
      - store_artifacts:
          path: coverage